CREATE TABLE users ( 
	user_id 			VARCHAR2(20)	NOT NULL,
	password 		VARCHAR2(20)	NOT NULL,
	user_name 		VARCHAR2(50)	NOT NULL,
	birth			VARCHAR2(10),	
	phone 			VARCHAR2(20),
	email1			VARCHAR2(50),
	email2			VARCHAR2(30),
	post_No 		VARCHAR2(20),
	address1 			VARCHAR2(100),
	address2 			VARCHAR2(100),
	dog_no			NUMBER(10)	NOT NULL REFERENCES dog_breed_dic(dog_no),
	user_condition		VARCHAR2(20),
	join_date 		DATE,	
	recently_date		DATE,
	leave_date		DATE,
	leave_reason  		VARCHAR(3),
	role			VARCHAR(10)	 DEFAULT 'user',
	sns_naver_id		VARCHAR(20),
	sns_kakao_id		VARCHAR(20),
	sns_google_id		VARCHAR(20),
	sns_facebook_id VARCHAR(20),
	PRIMARY KEY(user_id)
);
